name: fleetcommander

services:
  postgres:
    image: postgis/postgis:16-3.4
    platform: linux/amd64
    container_name: fleetcommander_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: fleetcommander_db
    ports:
      - "5435:5432"
    volumes:
      - fleet_pg_data:/var/lib/postgresql/data
    networks:
      - fleet_network

  redis:
    image: redis:7-alpine
    container_name: fleetcommander_redis
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6385:6379"
    volumes:
      - fleet_redis_data:/data
    networks:
      - fleet_network

volumes:
  fleet_pg_data:
  fleet_redis_data:

networks:
  fleet_network:
    driver: bridge
